ALTER TABLE "CallContact" ADD COLUMN IF NOT EXISTS "zone" TEXT NOT NULL DEFAULT '';
ALTER TABLE "CallContact" ADD COLUMN IF NOT EXISTS "district" TEXT NOT NULL DEFAULT '';
ALTER TABLE "CallContact" ADD COLUMN IF NOT EXISTS "halka" TEXT NOT NULL DEFAULT '';
ALTER TABLE "CallContact" ADD COLUMN IF NOT EXISTS "villageWard" TEXT NOT NULL DEFAULT '';
